spring:
  application:
    name: edunova-backend
  
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/edunova
    username: admin
    password: secret123
    
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql

logging:
  level:
    com.edunova: DEBUG

server:
  port: 8080
